-- Explore All Objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES


-- Explore All Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';

--============================================================================================

-- Explore All Countries our customers come from.
SELECT DISTINCT country FROM gold.dim_customers

-- Explore All the Categories "The Major Divisions"
SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products
ORDER BY 1,2;

--============================================================================================

-- Find the date of the first and last order
-- How many years of sales are avaiable
SELECT 
	MIN(order_date) AS first_order_date, 
	MAX(order_date) AS last_order_date,
	DATEDIFF(year,MIN(order_date) , MAX(order_date)) AS order_range_years
FROM gold.fact_sales;

-- Find the youngest and the oldest customer
SELECT
	MIN(birthdate) AS oldest_birthdate,
	DATEDIFF(year,MIN(birthdate), GETDATE()) AS oldest_cust_age,
	MAX(birthdate) AS youngest_birthdate,
	DATEDIFF(year,MAX(birthdate), GETDATE()) AS youngest_cust_age
FROM gold.dim_customers;

--============================================================================================

-- Find the Total Sales
SELECT SUM(sales_amount) AS Total_Sales FROM gold.fact_sales AS Total_Sales;

-- Find how many Items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales;

-- Find the average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales;

-- Find the Total number of Orders
SELECT COUNT(order_number) AS total_order FROM gold.fact_sales
SELECT COUNT(DISTINCT order_number) AS total_order FROM gold.fact_sales;

-- Find the total number of products
SELECT COUNT(product_key) AS total_products FROM gold.dim_products
SELECT COUNT(DISTINCT product_key) AS total_products FROM gold.dim_products;

-- Find the total number of customers
SELECT COUNT(customer_key) AS total FROM gold.dim_customers;

-- Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total FROM gold.fact_sales;
 

 -- GENERATE A REPORT THAT SHOWS ALL KEY METRICS OF THE BUSINESS
 SELECT 'Total Sales' AS measure_name,SUM(sales_amount) AS measure_value FROM gold.fact_sales AS Total_Sales
 UNION ALL 
 SELECT 'Total Quantity' , SUM(quantity) FROM gold.fact_sales
 UNION ALL 
 SELECT 'AVG Price' , AVG(price) FROM gold.fact_sales
 UNION ALL 
 SELECT 'Total No Order' , COUNT(DISTINCT order_number) FROM gold.fact_sales
 UNION ALL
 SELECT 'Total No Product' ,COUNT(DISTINCT product_key) FROM gold.dim_products
 UNION ALL
 SELECT 'Total No Customers',COUNT(customer_key)  FROM gold.dim_customers;

 --============================================================================================

 -- Find the total customers by countries
SELECT 
	country,
	COUNT(customer_key) as total_customer
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customer DESC;

-- Find the total customers by gender
SELECT 
	gender,
	COUNT(customer_key) as total_customer
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customer DESC;

-- Find total products by category
SELECT 
	category,
	COUNT(product_key) as total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT 
	category,
	AVG(cost) as avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category? 
SELECT 
	p.category,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY P.category
ORDER BY total_revenue DESC;

-- Find total revenue is generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
c.country,
SUM(f.quantity) AS total_sold_item
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_item DESC;
